### ISSUE TITLE
PRs from forks are missed by required-labels

### ISSUE THREAD

**Issue by dannyroberts** [dimagi/required-labels#12]
@proteusvacuum

**Comment by proteusvacuum** [comment]
The PR in question (https://github.com/dimagi/commcare-hq/pull/19061/commits/87a0a667590f491e77502e8627a4e16d43acc7a2) is returning a `404` from `required-labels`.

https://github.com/dimagi/commcare-hq/settings/hooks/17560961
Can see delivery with ID `e71c7af0-f494-11e7-8330-ce103811b736`
